from fpdf import FPDF
from datetime import datetime
import os

os.makedirs('static/reports', exist_ok=True)

class CardioReport(FPDF):
    def header(self):
        self.set_fill_color(139, 0, 0)
        self.rect(0, 0, 210, 28, 'F')
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(255, 255, 255)
        self.set_y(8)
        self.cell(0, 12, 'CardioInsight - Heart Disease Risk Report', align='C')
        self.set_font('Helvetica', '', 9)
        self.set_text_color(255, 200, 200)
        self.cell(0, 6, 'AI-Powered Cardiovascular Risk Assessment', align='C', ln=True)
        self.ln(4)

    def footer(self):
        self.set_y(-18)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5,
            'DISCLAIMER: This report is for informational purposes only and does not replace professional medical advice.',
            align='C', ln=True)
        self.cell(0, 5, f'Generated by CardioInsight  |  Page {self.page_no()}', align='C')

def generate_report(name, age, sex, chol, bp, hr, smoking, exercise, exang, ca, risk, label, recs):
    pdf = CardioReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Patient Info Box ──────────────────────────────────────
    pdf.set_fill_color(245, 245, 250)
    pdf.set_draw_color(200, 200, 210)
    pdf.set_line_width(0.3)
    pdf.rect(12, 32, 186, 52, 'FD')

    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(80, 0, 0)
    pdf.set_xy(15, 35)
    pdf.cell(0, 8, 'Patient Information', ln=True)

    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    sex_str = 'Male' if sex == 1 else 'Female'
    smoke_str = 'Yes' if smoking == 1 else 'No'
    ex_str = 'Yes' if exercise == 1 else 'No'
    date_str = datetime.now().strftime('%d %B %Y, %I:%M %p')

    info = [
        ('Name', name), ('Age', f'{age} years'), ('Sex', sex_str),
        ('Date', date_str)
    ]
    col_w = 90
    pdf.set_x(15)
    for i, (k, v) in enumerate(info):
        if i % 2 == 0 and i > 0:
            pdf.set_x(15)
        x = 15 + (i % 2) * col_w
        pdf.set_xy(x, pdf.get_y())
        pdf.set_font('Helvetica', 'B', 10)
        pdf.cell(30, 7, f'{k}:')
        pdf.set_font('Helvetica', '', 10)
        pdf.cell(col_w - 32, 7, str(v), ln=(i % 2 == 1))
    pdf.ln(2)

    # ── Risk Score Box ────────────────────────────────────────
    if label == 'High Risk':
        r, g, b = 231, 76, 60
    elif label == 'Moderate Risk':
        r, g, b = 243, 156, 18
    else:
        r, g, b = 39, 174, 96

    pdf.set_xy(12, 90)
    pdf.set_fill_color(r, g, b)
    pdf.rect(12, 90, 186, 32, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 26)
    pdf.set_xy(12, 93)
    pdf.cell(186, 12, f'Risk Score: {risk}%  --  {label}', align='C', ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(186, 8, 'Based on Random Forest ML Model (Accuracy: 87.90%)', align='C', ln=True)

    # ── Vitals Table ──────────────────────────────────────────
    pdf.set_xy(12, 130)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(80, 0, 0)
    pdf.cell(0, 8, 'Health Indicators', ln=True)

    headers = ['Indicator', 'Your Value', 'Normal Range', 'Status']
    col_widths = [60, 40, 50, 36]

    vitals = [
        ('Cholesterol', f'{chol} mg/dl', '< 200 mg/dl',  '! High' if chol > 200 else 'OK Normal'),
        ('Blood Pressure', f'{bp} mmHg',   '< 130 mmHg',   '! High' if bp > 130 else 'OK Normal'),
        ('Max Heart Rate', f'{hr} bpm',    '> 100 bpm',    '! Low'  if hr < 100 else 'OK Normal'),
        ('Smoking',  'Yes' if smoking else 'No',   'Non-smoker',   '! Risk' if smoking else 'OK Good'),
        ('Exercise', 'Yes' if exercise else 'No',  'Regular',      'OK Good' if exercise else '! Risk'),
    ]

    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_fill_color(139, 0, 0)
    pdf.set_text_color(255, 255, 255)
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 7, h, border=0, fill=True)
    pdf.ln()

    pdf.set_font('Helvetica', '', 9)
    for i, row in enumerate(vitals):
        fill = i % 2 == 0
        pdf.set_fill_color(245, 245, 250)
        for w, val in zip(col_widths, row):
            if '⚠' in str(val):
                pdf.set_text_color(200, 50, 50)
            elif '✓' in str(val):
                pdf.set_text_color(39, 130, 70)
            else:
                pdf.set_text_color(50, 50, 50)
            pdf.cell(w, 7, str(val), border=0, fill=fill)
        pdf.set_text_color(50, 50, 50)
        pdf.ln()

    # ── Recommendations ───────────────────────────────────────
    pdf.ln(4)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(80, 0, 0)
    pdf.cell(0, 8, 'Personalized Recommendations', ln=True)

    priority_colors = {
        'urgent': (231, 76, 60),
        'high':   (230, 126, 34),
        'medium': (52, 152, 219),
        'low':    (39, 174, 96),
    }
    for icon, text, priority in recs:
        r2, g2, b2 = priority_colors.get(priority, (100, 100, 100))
        pdf.set_fill_color(r2, g2, b2)
        pdf.rect(12, pdf.get_y(), 4, 7, 'F')
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(50, 50, 50)
        pdf.set_x(20)
        # Strip non-latin chars for PDF compatibility
        clean_text = text.encode('latin-1', errors='ignore').decode('latin-1')
        pdf.cell(0, 7, f'>>  {clean_text}', ln=True)
        pdf.ln(1)

    safe_name = name.replace(' ', '_').replace('/', '_')
    path = f'static/reports/report_{safe_name}.pdf'
    pdf.output(path)
    return path
